### ISSUE TITLE
Docker-Build Action: normalize tags causes only the first tag to be used

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/gh-automation#17]
With
https://github.com/keptn/gh-automation/blob/c403b07988f8fe5ab215a1dea4dd0204f3733805/.github/actions/docker-build/action.yaml#L70-L73

The following step does not build all tags, but only the first one  (without env.DATETIME)

```yaml
      - name: Docker Build
        id: docker_build
        uses: keptn/gh-automation/.github/actions/docker-build@v1.5.1
        with:
          TAGS: |
            ${{ env.DOCKER_ORGANIZATION }}/${{ env.IMAGE }}:${{ env.VERSION }}
            ${{ env.DOCKER_ORGANIZATION }}/${{ env.IMAGE }}:${{ env.VERSION }}.${{ env.DATETIME }}
          BUILD_ARGS: |
            version=${{ env.VERSION }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          PUSH: ${{(github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository)}}

```

# Expected behaviour

All Tags listed in TAGS are built (and pushed)

# Analysis

I was able to reproduce this with the following job:
```yaml
      # Runs a single command using the runners shell
      - name: Before
        run: echo Tags='${{ env.TAGS }}'

      - name: Normalize TAGS
        shell: bash
        id: normalize_tags
        run: echo "::set-output name=tags::$(echo '${{ env.TAGS }}' | tr '[:upper:]' '[:lower:]')"

      # Runs a set of commands using the runners shell
      - name: After
        run: echo Tags='${{ steps.normalize_tags.outputs.tags }}'
```

![image](https://user-images.githubusercontent.com/56065213/161038425-372eb6f7-3c17-4bd0-8395-940c73caddb5.png)
