### ISSUE TITLE
Docker-Build Action: normalize tags causes problems with upper-cased tags

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/gh-automation#19]
With
https://github.com/keptn/gh-automation/blob/c403b07988f8fe5ab215a1dea4dd0204f3733805/.github/actions/docker-build/action.yaml#L70-L73

The following step builds all tags, but tags with upper-cased characters will be lower-cased, which breaks certain integrations, e.g.:

```yaml
      - name: Docker Build
        id: docker_build
        uses: keptn/gh-automation/.github/actions/docker-build@v1.5.2
        with:
          TAGS: |
            ${{ env.DOCKER_ORGANIZATION }}/${{ env.IMAGE }}:PR-123
            ${{ env.DOCKER_ORGANIZATION }}/${{ env.IMAGE }}:PR-123.${{ env.DATETIME }}
          BUILD_ARGS: |
            version=${{ env.VERSION }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
```

In the above example, the tags will be normaliezd from "PR-123" to "pr-123".

In our helm-charts we are expecting the tags to be "PR-123" though, so we end up getting image pull back offs when installing helm charts.

# Expected behaviour

All Tags listed in TAGS are built the correct way.
